[build]
  base = "unicart_app"
  publish = "build/web"
  command = """
  if [ ! -d "flutter" ]; then git clone https://github.com/flutter/flutter.git -b stable; fi
  export PATH="$PATH:$(pwd)/flutter/bin"
  flutter doctor
  flutter pub get
  flutter build web --release --base-href /
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200